//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BabySitter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BabySitter()
        {
            this.Favorite = new HashSet<Favorite>();
            this.FixedBabySitter = new HashSet<FixedBabySitter>();
            this.Group = new HashSet<Group>();
            this.Invaite = new HashSet<Invaite>();
            this.LanguageToMember = new HashSet<LanguageToMember>();
            this.MemberGroup = new HashSet<MemberGroup>();
            this.OpenBabySitter = new HashSet<OpenBabySitter>();
            this.TrainingToMember = new HashSet<TrainingToMember>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> SalaryHour { get; set; }
        public string Password { get; set; }
        public System.DateTime BornDate { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public bool SpecialChildren { get; set; }
        public bool ShowTell { get; set; }
        public bool ShowMail { get; set; }
        public int status { get; set; }
        public System.DateTime StartWork { get; set; }
        public int LowAgeChildren { get; set; }
        public int HighAgeChildren { get; set; }
        public bool license { get; set; }
        public bool Household { get; set; }
        public bool CollectingChildren { get; set; }
        public string More { get; set; }
        public int Experience { get; set; }
        public int MaxChildren { get; set; }
        public string Is { get; set; }
        public bool IsShowFromGroups { get; set; }
    
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedBabySitter> FixedBabySitter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invaite> Invaite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageToMember> LanguageToMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGroup> MemberGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenBabySitter> OpenBabySitter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingToMember> TrainingToMember { get; set; }
    }
}
