//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedDate
    {
        public int Id { get; set; }
        public int IdMother { get; set; }
        public int IdBabySitter { get; set; }
        public System.DateTime Date { get; set; }
        public int IdPart { get; set; }
        public string Detailst { get; set; }
    }
}
