//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.MemberGroup = new HashSet<MemberGroup>();
        }
    
        public int GroupId { get; set; }
        public Nullable<int> IdMotherManager { get; set; }
        public Nullable<int> IdBabySitterManager { get; set; }
        public string NameGroup { get; set; }
        public string Password { get; set; }
    
        public virtual BabySitter BabySitter { get; set; }
        public virtual Mother Mother { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGroup> MemberGroup { get; set; }
    }
}
