//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BabySitterDBEntities : DbContext
    {
        public BabySitterDBEntities()
            : base("name=BabySitterDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BabySitter> BabySitter { get; set; }
        public virtual DbSet<Favorite> Favorite { get; set; }
        public virtual DbSet<FixedBabySitter> FixedBabySitter { get; set; }
        public virtual DbSet<FixedDate> FixedDate { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Invaite> Invaite { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<LanguageToMember> LanguageToMember { get; set; }
        public virtual DbSet<MemberGroup> MemberGroup { get; set; }
        public virtual DbSet<Mother> Mother { get; set; }
        public virtual DbSet<OpenBabySitter> OpenBabySitter { get; set; }
        public virtual DbSet<PartOfDay> PartOfDay { get; set; }
        public virtual DbSet<RequestMother> RequestMother { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<TrainingToMember> TrainingToMember { get; set; }
    }
}
