//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mother
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mother()
        {
            this.Favorite = new HashSet<Favorite>();
            this.Group = new HashSet<Group>();
            this.Invaite = new HashSet<Invaite>();
            this.Invaite1 = new HashSet<Invaite>();
            this.MemberGroup = new HashSet<MemberGroup>();
            this.RequestMother = new HashSet<RequestMother>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public string Phone { get; set; }
        public int NumChildren { get; set; }
        public Nullable<int> SalaryHour { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public string More { get; set; }
        public int LowAgeChildren { get; set; }
        public int HighAgeChildren { get; set; }
        public string City { get; set; }
        public Nullable<bool> ShowMail { get; set; }
        public Nullable<bool> ShowTell { get; set; }
        public bool IsShowFromGroups { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invaite> Invaite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invaite> Invaite1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGroup> MemberGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestMother> RequestMother { get; set; }
    }
}
