//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingToMember
    {
        public int Id { get; set; }
        public int IdTraining { get; set; }
        public int IdMember { get; set; }
    
        public virtual BabySitter BabySitter { get; set; }
        public virtual Training Training { get; set; }
    }
}
